#!/usr/bin/env python3
from pathlib import Path

SRC = Path('render_jobs/house_step_v3/House_Extrusion_3D_STEP_BY_STEP_V4_CROQUIS_PROTOCOL.py')
DST = Path('render_jobs/house_step_v3/House_Extrusion_3D_STEP_BY_STEP_V5_CLOSED_CROQUIS_LATEX.py')
s = SRC.read_text(encoding='utf-8')

s=s.replace('Croquis protocol V1 — deterministic camera + semantic pacing states.', 'Croquis protocol V2 — closed CAD profiles + LaTeX typography + semantic pacing.')
s=s.replace('CAMERA_SETTLE_PAUSE = 0.75\n    MICRO_PAUSE = 0.40\n    CONSTRUCTION_PAUSE = 0.70\n    READING_PAUSE = 1.20\n    EXPLANATION_PAUSE = 1.55\n    FINAL_OBSERVATION_PAUSE = 1.90',
'''CAMERA_SETTLE_PAUSE = 1.00\n    MICRO_PAUSE = 0.65\n    CONSTRUCTION_PAUSE = 1.10\n    READING_PAUSE = 1.75\n    EXPLANATION_PAUSE = 2.35\n    FINAL_OBSERVATION_PAUSE = 2.80\n\n    EXTERNAL_WALL_OPACITY = 0.38\n    INTERNAL_WALL_OPACITY = 0.94''')
s=s.replace('''    def text(self, content, size=28, weight=NORMAL, color=BLACK_TEXT):\n        return Text(content, font_size=size, weight=weight, color=color)\n''', '''    def text(self, content, size=28, weight=NORMAL, color=BLACK_TEXT):\n        \"\"\"LaTeX typography for every technical label/HUD string.\"\"\"\n        safe = (\n            content.replace(\"·\", \"--\")\n            .replace(\"−\", \"-\")\n            .replace(\"→\", r\"$\\rightarrow$\")\n        )\n        if weight == BOLD and \"$\" not in safe:\n            safe = r\"\\textbf{\" + safe + \"}\"\n        return Tex(safe, font_size=size, color=color)\n''')
old='''    def wall_trace(self, z):\n        w, d = self.HOUSE_W, self.HOUSE_D\n        p = [\n            [-w/2, -d/2, z], [w/2, -d/2, z],\n            [w/2, d/2, z], [-w/2, d/2, z]\n        ]\n        exterior = VGroup(*[\n            Line(p[i], p[(i + 1) % 4], color=SKETCH, stroke_width=3.6)\n            for i in range(4)\n        ])\n        specs = [\n            ((0.70, -2.55), (0.70, 2.35)),\n            ((-4.05, 0.75), (0.70, 0.75)),\n            ((0.70, 0.75), (4.05, 0.75)),\n            ((-1.90, 0.75), (-1.90, 2.70)),\n        ]\n        interior = VGroup(*[\n            Line([a[0], a[1], z], [b[0], b[1], z], color=SKETCH, stroke_width=3.0)\n            for a, b in specs\n        ])\n        return exterior, interior\n'''
new='''    def closed_wall_profile(self, dims, center, z, stroke_width=3.2, fill_opacity=0.045):\n        \"\"\"Closed XY footprint matching the exact wall solid that will be extruded.\"\"\"\n        dx, dy, _ = dims\n        rect = Rectangle(\n            width=dx, height=dy, stroke_color=SKETCH, stroke_width=stroke_width,\n            fill_color=SKETCH, fill_opacity=fill_opacity,\n        )\n        rect.move_to([center[0], center[1], z])\n        return rect\n\n    def wall_trace(self, z):\n        \"\"\"Return only CLOSED wall profiles; no open centerlines are allowed.\"\"\"\n        ext_specs, int_specs = self.wall_specs()\n        exterior = VGroup(*[\n            self.closed_wall_profile(dims, center, z, stroke_width=3.6, fill_opacity=0.035)\n            for dims, center in ext_specs\n        ])\n        interior = VGroup(*[\n            self.closed_wall_profile(dims, center, z, stroke_width=3.3, fill_opacity=0.065)\n            for dims, center in int_specs\n        ])\n        return exterior, interior\n'''
assert old in s
s=s.replace(old,new)
s=s.replace('''    def make_wall_extrusion(self, specs):\n        seeds, targets = [], []\n        h0 = 0.025\n        for dims, center in specs:\n            dx, dy, dz = dims\n            seeds.append(self.box((dx, dy, h0), (center[0], center[1], self.FLOOR_Z + h0/2), WALL, 0.96))\n            targets.append(self.box(dims, center, WALL, 0.97))\n        return seeds, targets\n''', '''    def make_wall_extrusion(self, specs, opacity):\n        seeds, targets = [], []\n        h0 = 0.025\n        for dims, center in specs:\n            dx, dy, dz = dims\n            seeds.append(self.box((dx, dy, h0), (center[0], center[1], self.FLOOR_Z + h0/2), WALL, opacity))\n            targets.append(self.box(dims, center, WALL, opacity))\n        return seeds, targets\n''')
s=s.replace('WALL, 0.97)', 'WALL, self.EXTERNAL_WALL_OPACITY)')
s=s.replace('''        for mob in (title, subtitle, rule, box, phase, legend):\n            self.add_fixed_in_frame_mobjects(mob)\n        return {\"box\": box, \"text\": phase}\n''', '''        for mob in (title, subtitle, rule, box, phase, legend):\n            self.add_fixed_in_frame_mobjects(mob)\n        self.play(Write(title), Write(subtitle), Write(phase), Write(add_text), Write(rem_text), run_time=1.85)\n        self.wait(self.READING_PAUSE)\n        return {\"box\": box, \"text\": phase}\n''')
s=s.replace('''        self.add_fixed_in_frame_mobjects(new)\n        self.play(FadeOut(old), FadeIn(new), run_time=0.38)\n''','''        self.add_fixed_in_frame_mobjects(new)\n        self.play(FadeOut(old), Write(new), run_time=0.72)\n        self.wait(self.MICRO_PAUSE)\n''')
s=s.replace('''        group = VGroup(box, label)\n        self.add_fixed_in_frame_mobjects(group)\n        self.play(FadeIn(group, shift=UP*0.08), run_time=0.45)\n        return group\n''','''        group = VGroup(box, label)\n        self.add_fixed_in_frame_mobjects(group)\n        self.play(FadeIn(box, shift=UP*0.08), Write(label), run_time=0.85)\n        self.wait(self.MICRO_PAUSE)\n        return group\n''')
s=s.replace('''        ext_seeds, ext_targets = self.make_wall_extrusion(ext_specs)\n        int_seeds, int_targets = self.make_wall_extrusion(int_specs)\n''','''        ext_seeds, ext_targets = self.make_wall_extrusion(ext_specs, self.EXTERNAL_WALL_OPACITY)\n        int_seeds, int_targets = self.make_wall_extrusion(int_specs, self.INTERNAL_WALL_OPACITY)\n''')
s=s.replace('''        self.play(LaggedStart(*[Create(m) for m in ext_trace], lag_ratio=0.12), run_time=1.8)\n        self.wait(self.CONSTRUCTION_PAUSE)\n        self.play(LaggedStart(*[Create(m) for m in int_trace], lag_ratio=0.12), run_time=1.6)\n        self.wait(self.CONSTRUCTION_PAUSE)\n''','''        self.play(LaggedStart(*[Create(m) for m in ext_trace], lag_ratio=0.18), run_time=2.65)\n        self.wait(self.CONSTRUCTION_PAUSE)\n        for profile in int_trace:\n            self.play(Create(profile), run_time=1.15)\n            self.wait(self.MICRO_PAUSE)\n        self.wait(self.EXPLANATION_PAUSE)\n''')
s=s.replace('''        self.play(LaggedStart(*[Create(m) for m in col_profiles], lag_ratio=0.07), run_time=2.0)\n        self.wait(self.FINAL_OBSERVATION_PAUSE)\n''','''        self.play(LaggedStart(*[Create(m) for m in col_profiles], lag_ratio=0.07), run_time=2.45)\n        self.wait(self.FINAL_OBSERVATION_PAUSE)\n''')
s=s.replace('''        self.play(FadeIn(summary, shift=UP*0.12), run_time=0.8)\n        self.wait(4.0)\n''','''        self.play(FadeIn(summary_box, shift=UP*0.12), Write(l1), Write(l2), run_time=1.55)\n        self.wait(5.2)\n''')
s=s.replace('self.wait(1.1)\n        self.remove_note(note)', 'self.wait(1.8)\n        self.remove_note(note)', 1)
s=s.replace('self.wait(1.0)\n        self.remove_note(note)', 'self.wait(1.7)\n        self.remove_note(note)', 1)
s=s.replace('self.wait(5.0)', 'self.wait(6.5)', 1)
s=s.replace('Croquis camera protocol V1', 'Croquis camera protocol V2')
s=s.replace('10. Final orbit + CAD operation summary.\n"""', '10. Final orbit + CAD operation summary.\n\nV5 refinements: closed wall croquis, LaTeX/Write typography, slower pacing, transparent exterior walls.\n"""')
DST.write_text(s, encoding='utf-8')
print(DST)
