#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 3:
    raise SystemExit('usage: apply_senior_qa_v5.py V3_BASE.py V5_OUT.py')
base = Path(sys.argv[1])
out = Path(sys.argv[2])
src = base.read_text(encoding='utf-8')

src = src.replace(
    'Senior QA V3: preserves V2 improvements and fixes scale-number visibility plus read-example annotation collisions.',
    'Senior QA V5: source-level final pass from persisted V3; fixes IQR/whisker annotation spacing and duplicate outlier highlighting.',
    1,
)

needle = '''    def _fmt(self, value: float) -> str:\n        if abs(value - round(value)) < 1e-9:\n            return str(int(round(value)))\n        return f"{value:.1f}"\n\n'''
insert = needle + '''    def assert_no_bbox_overlap(self, a: Mobject, b: Mobject, label: str, pad: float = 0.04) -> None:\n        """Fail the render gate if two critical annotations occupy the same visual box."""\n        a_l, a_r = a.get_left()[0] - pad, a.get_right()[0] + pad\n        a_b, a_t = a.get_bottom()[1] - pad, a.get_top()[1] + pad\n        b_l, b_r = b.get_left()[0] - pad, b.get_right()[0] + pad\n        b_b, b_t = b.get_bottom()[1] - pad, b.get_top()[1] + pad\n        separated = (a_r < b_l) or (b_r < a_l) or (a_t < b_b) or (b_t < a_b)\n        if not separated:\n            raise ValueError(f"{label}: critical annotations overlap")\n\n'''
assert needle in src
src = src.replace(needle, insert, 1)

old_iqr = '''    def compare_iqr(self) -> None:\n        self.set_header(\n            8,\n            "COMPARE THE MIDDLE 50% WITH IQR",\n            "The box width is meaningful only because both boxplots use the same numerical scale.",\n        )\n        axis = self.compare_axis\n        a, b = self.compare_a, self.compare_b\n        brace_a = BraceBetweenPoints(\n            [axis.n2p(a.q1)[0], 0.20, 0],\n            [axis.n2p(a.q3)[0], 0.20, 0],\n            direction=DOWN,\n            color=BLACK_LINE,\n        )\n        brace_b = BraceBetweenPoints(\n            [axis.n2p(b.q1)[0], -1.28, 0],\n            [axis.n2p(b.q3)[0], -1.28, 0],\n            direction=DOWN,\n            color=BLACK_LINE,\n        )\n        lab_a = self.math(r"IQR_A=11.5", 27).next_to(brace_a, DOWN, buff=0.08)\n        lab_b = self.math(r"IQR_B=5", 27).next_to(brace_b, DOWN, buff=0.08)\n        statement = self.text(\n            "Group B has a smaller IQR, so its central observations are more tightly clustered.",\n            26,\n            BOLD,\n        ).to_edge(DOWN, buff=0.42)\n        self.fit(statement, 13.8, 0.55)\n        self.play(GrowFromCenter(brace_a), FadeIn(lab_a), run_time=RUN_NORMAL)\n        self.play(GrowFromCenter(brace_b), FadeIn(lab_b), run_time=RUN_NORMAL)\n        self.play(FadeIn(statement, shift=UP * 0.06), run_time=RUN_NORMAL)\n        self.wait(PAUSE_EXPLAIN)\n        self.play(FadeOut(VGroup(brace_a, brace_b, lab_a, lab_b, statement)), run_time=RUN_QUICK)\n\n'''
new_iqr = '''    def compare_iqr(self) -> None:\n        self.set_header(\n            8,\n            "COMPARE THE MIDDLE 50% WITH IQR",\n            "The box width is meaningful only because both boxplots use the same numerical scale.",\n        )\n        axis = self.compare_axis\n        a, b = self.compare_a, self.compare_b\n\n        # V5: reserve separate vertical lanes for each IQR annotation.\n        brace_a = BraceBetweenPoints(\n            [axis.n2p(a.q1)[0], 0.22, 0],\n            [axis.n2p(a.q3)[0], 0.22, 0],\n            direction=DOWN,\n            color=BLACK_LINE,\n        )\n        brace_b = BraceBetweenPoints(\n            [axis.n2p(b.q1)[0], -1.22, 0],\n            [axis.n2p(b.q3)[0], -1.22, 0],\n            direction=DOWN,\n            color=BLACK_LINE,\n        )\n        lab_a = self.math(r"IQR_A=11.5", 30).move_to(\n            [(axis.n2p(a.q1)[0] + axis.n2p(a.q3)[0]) / 2, 1.38, 0]\n        )\n        lab_b = self.math(r"IQR_B=5", 30).next_to(brace_b, DOWN, buff=0.10)\n\n        critical = VGroup(brace_a, brace_b, lab_a, lab_b)\n        self.assert_content_safe(critical, "scene 08 IQR annotations")\n        self.assert_no_bbox_overlap(lab_a, self.compare_plot_a, "scene 08 A label versus A box", pad=0.02)\n        self.assert_no_bbox_overlap(lab_b, axis, "scene 08 B label versus common axis", pad=0.02)\n\n        statement = self.text(\n            "Group B has a smaller IQR, so its central observations are more tightly clustered.",\n            26,\n            BOLD,\n        ).to_edge(DOWN, buff=0.42)\n        self.fit(statement, 13.8, 0.55)\n        self.play(FadeIn(lab_a, shift=UP * 0.05), GrowFromCenter(brace_a), run_time=RUN_NORMAL)\n        self.play(GrowFromCenter(brace_b), FadeIn(lab_b, shift=DOWN * 0.05), run_time=RUN_NORMAL)\n        self.play(FadeIn(statement, shift=UP * 0.06), run_time=RUN_NORMAL)\n        self.wait(PAUSE_EXPLAIN)\n        self.play(FadeOut(VGroup(brace_a, brace_b, lab_a, lab_b, statement)), run_time=RUN_QUICK)\n\n'''
assert old_iqr in src
src = src.replace(old_iqr, new_iqr, 1)

old_whiskers = '''    def compare_whiskers(self) -> None:\n        self.set_header(\n            9,\n            "READ THE REGULAR EXTERIOR SPREAD",\n            "Whisker lengths describe how far the regular observations extend outside the middle 50%; they are not fence distances.",\n        )\n        axis = self.compare_axis\n        labels = VGroup(\n            self.text("A lower: 40 to 45.5", 23, BOLD).move_to([axis.n2p(43)[0], 1.42, 0]),\n            self.text("A upper: 57 to 63", 23, BOLD).move_to([axis.n2p(60)[0], 1.42, 0]),\n            self.text("B lower: 49 to 52.5", 23, BOLD).move_to([axis.n2p(50.7)[0], -1.55, 0]),\n            self.text("B upper: 57.5 to 58", 23, BOLD).move_to([axis.n2p(58)[0], -1.55, 0]),\n        )\n        statement = self.text(\n            "Group A is fairly balanced outside the box; Group B has a very short upper regular whisker.",\n            23,\n            BOLD,\n        ).move_to(UP * 2.05)\n        self.fit(statement, 12.8, 0.50)\n        self.play(FadeOut(self.compare_data_labels), FadeIn(statement), run_time=RUN_NORMAL)\n        self.play(LaggedStart(*[FadeIn(label) for label in labels], lag_ratio=0.15), run_time=RUN_SLOW)\n        self.wait(PAUSE_WORK)\n        self.play(FadeOut(labels), FadeOut(statement), run_time=RUN_QUICK)\n\n'''
new_whiskers = '''    def compare_whiskers(self) -> None:\n        self.set_header(\n            9,\n            "READ THE REGULAR EXTERIOR SPREAD",\n            "Whisker lengths describe how far the regular observations extend outside the middle 50%; they are not fence distances.",\n        )\n        axis = self.compare_axis\n\n        a_lower = self.text("A lower: 40 to 45.5", 24, BOLD).move_to([axis.n2p(43)[0], 1.45, 0])\n        a_upper = self.text("A upper: 57 to 63", 24, BOLD).move_to([axis.n2p(60)[0], 1.45, 0])\n        b_lower = self.text("B lower: 49 to 52.5", 24, BOLD).move_to([axis.n2p(50.5)[0], -1.53, 0])\n        b_upper = self.text("B upper: 57.5 to 58", 24, BOLD).move_to([axis.n2p(64)[0], -0.80, 0])\n        b_upper_leader = Line(\n            [axis.n2p(58)[0] + 0.08, -0.80, 0],\n            [b_upper.get_left()[0] - 0.10, -0.80, 0],\n            color=MID_GRAY,\n            stroke_width=1.8,\n        )\n        labels = VGroup(a_lower, a_upper, b_lower, b_upper, b_upper_leader)\n        self.assert_content_safe(labels, "scene 09 whisker callouts")\n        self.assert_no_bbox_overlap(b_lower, b_upper, "scene 09 Group B callouts", pad=0.06)\n        self.assert_no_bbox_overlap(b_lower, axis, "scene 09 lower-B label versus axis", pad=0.02)\n\n        statement = self.text(\n            "Group A is fairly balanced outside the box; Group B has a very short upper regular whisker.",\n            24,\n            BOLD,\n        ).move_to(UP * 2.05)\n        self.fit(statement, 12.8, 0.52)\n        self.play(FadeOut(self.compare_data_labels), FadeIn(statement), run_time=RUN_NORMAL)\n        self.play(FadeIn(a_lower), FadeIn(a_upper), run_time=RUN_NORMAL)\n        self.play(FadeIn(b_lower), Create(b_upper_leader), FadeIn(b_upper), run_time=RUN_NORMAL)\n        self.wait(PAUSE_WORK)\n        self.play(FadeOut(labels), FadeOut(statement), run_time=RUN_QUICK)\n\n'''
assert old_whiskers in src
src = src.replace(old_whiskers, new_whiskers, 1)

old_outlier = '''        out_x = axis.n2p(75)[0]\n        out_circle = Circle(radius=0.18, stroke_color=BLACK_LINE, stroke_width=2.4, fill_opacity=0).move_to([out_x, -0.80, 0])\n        out_label = self.text("75 is plotted separately", 24, BOLD).next_to(out_circle, UP, buff=0.22)\n        whisker_label = self.text("upper whisker ends at 58", 23).move_to([axis.n2p(58)[0], -0.15, 0])\n        self.play(Create(guide), FadeIn(uf_label), run_time=RUN_NORMAL)\n        self.play(Create(out_circle), FadeIn(out_label), FadeIn(whisker_label), run_time=RUN_NORMAL)\n        self.wait(PAUSE_WORK)\n        self.play(FadeOut(VGroup(guide, uf_label, out_circle, out_label, whisker_label)), run_time=RUN_QUICK)\n'''
new_outlier = '''        outlier_mark = self.compare_plot_b[6][0]\n        out_label = self.text("75 is plotted separately", 24, BOLD).next_to(outlier_mark, UP, buff=0.22)\n        whisker_label = self.text("upper whisker ends at 58", 23).move_to([axis.n2p(62)[0], -0.18, 0])\n        self.assert_content_safe(VGroup(guide, uf_label, out_label, whisker_label), "scene 11 outlier annotations")\n        self.play(Create(guide), FadeIn(uf_label), run_time=RUN_NORMAL)\n        self.play(\n            Circumscribe(outlier_mark, color=BLACK_LINE, buff=0.08),\n            FadeIn(out_label),\n            FadeIn(whisker_label),\n            run_time=RUN_NORMAL,\n        )\n        self.wait(PAUSE_WORK)\n        self.play(FadeOut(VGroup(guide, uf_label, out_label, whisker_label)), run_time=RUN_QUICK)\n'''
assert old_outlier in src
src = src.replace(old_outlier, new_outlier, 1)

src = src.replace('Statistics10_IQR_Class02_Compare_Boxplots_FINAL.py Statistics10IQRClass02CompareBoxplotsFinal', 'Statistics10_IQR_Class02_Compare_Boxplots_SENIOR_QA_V5.py Statistics10IQRClass02CompareBoxplotsFinal')

out.write_text(src, encoding='utf-8')
print(f'generated {out} from {base}')
