#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 3:
    raise SystemExit('usage: apply_senior_qa_v6.py V5_BASE.py V6_OUT.py')
base=Path(sys.argv[1]); out=Path(sys.argv[2])
src=base.read_text(encoding='utf-8')
src=src.replace(
    'Senior QA V5: source-level final pass from persisted V3; fixes IQR/whisker annotation spacing and duplicate outlier highlighting.',
    'Senior QA V6: final manual-audit pass from persisted V5; separates Scene 11 fence, whisker, and outlier annotations into independent lanes.',
    1,
)
old='''    def inspect_outliers(self) -> None:\n        self.set_header(\n            11,\n            "OUTLIERS MUST STAY SEPARATE",\n            "An outlier is still part of the dataset, but the modified whisker stops at the most extreme regular observation.",\n        )\n        b = self.compare_b\n        axis = self.compare_axis\n        x_uf = axis.n2p(b.uf)[0]\n        guide = DashedLine([x_uf, -1.50, 0], [x_uf, -0.12, 0], color=MID_GRAY, stroke_width=2)\n        uf_label = self.math(r"UF_B=65", 26).next_to(guide, UP, buff=0.06)\n        outlier_mark = self.compare_plot_b[6][0]\n        out_label = self.text("75 is plotted separately", 24, BOLD).next_to(outlier_mark, UP, buff=0.22)\n        whisker_label = self.text("upper whisker ends at 58", 23).move_to([axis.n2p(62)[0], -0.18, 0])\n        self.assert_content_safe(VGroup(guide, uf_label, out_label, whisker_label), "scene 11 outlier annotations")\n        self.play(Create(guide), FadeIn(uf_label), run_time=RUN_NORMAL)\n        self.play(\n            Circumscribe(outlier_mark, color=BLACK_LINE, buff=0.08),\n            FadeIn(out_label),\n            FadeIn(whisker_label),\n            run_time=RUN_NORMAL,\n        )\n        self.wait(PAUSE_WORK)\n        self.play(FadeOut(VGroup(guide, uf_label, out_label, whisker_label)), run_time=RUN_QUICK)\n        # Comparison sequence ends here.\n        self.clear_stage()\n'''
new='''    def inspect_outliers(self) -> None:\n        self.set_header(\n            11,\n            "OUTLIERS MUST STAY SEPARATE",\n            "An outlier is still part of the dataset, but the modified whisker stops at the most extreme regular observation.",\n        )\n        b = self.compare_b\n        axis = self.compare_axis\n        x_uf = axis.n2p(b.uf)[0]\n        guide = DashedLine([x_uf, -1.45, 0], [x_uf, 0.18, 0], color=MID_GRAY, stroke_width=2)\n        # V6 manual-QA correction: three ideas, three non-overlapping visual lanes.\n        uf_label = self.math(r"UF_B=65", 27).move_to([x_uf, 0.48, 0])\n        outlier_mark = self.compare_plot_b[6][0]\n        out_label = self.text("75 is plotted separately", 24, BOLD).move_to([axis.n2p(75)[0], -0.20, 0])\n        whisker_label = self.text("upper whisker ends at 58", 23, BOLD).move_to([axis.n2p(58)[0], -1.48, 0])\n\n        annotations = VGroup(guide, uf_label, out_label, whisker_label)\n        self.assert_content_safe(annotations, "scene 11 outlier annotations")\n        self.assert_no_bbox_overlap(uf_label, out_label, "scene 11 fence label versus outlier label", pad=0.04)\n        self.assert_no_bbox_overlap(uf_label, whisker_label, "scene 11 fence label versus whisker label", pad=0.04)\n        self.assert_no_bbox_overlap(out_label, whisker_label, "scene 11 outlier label versus whisker label", pad=0.04)\n        self.assert_no_bbox_overlap(whisker_label, axis, "scene 11 whisker label versus axis", pad=0.02)\n\n        self.play(Create(guide), FadeIn(uf_label), run_time=RUN_NORMAL)\n        self.play(\n            FadeIn(whisker_label, shift=DOWN * 0.04),\n            Circumscribe(outlier_mark, color=BLACK_LINE, buff=0.08),\n            FadeIn(out_label, shift=UP * 0.04),\n            run_time=RUN_NORMAL,\n        )\n        self.wait(PAUSE_WORK)\n        self.play(FadeOut(annotations), run_time=RUN_QUICK)\n        # Comparison sequence ends here.\n        self.clear_stage()\n'''
assert old in src, 'Scene 11 block changed unexpectedly'
src=src.replace(old,new,1)
src=src.replace('Statistics10_IQR_Class02_Compare_Boxplots_SENIOR_QA_V5.py Statistics10IQRClass02CompareBoxplotsFinal', 'Statistics10_IQR_Class02_Compare_Boxplots_SENIOR_QA_V6.py Statistics10IQRClass02CompareBoxplotsFinal')
out.write_text(src,encoding='utf-8')
print(f'generated {out} from {base}')
